### PR TITLE
ui/ingame_scoreboard: turn playername into a span

### PR DESCRIPTION
**Pull request by illwieckz**
Port CSS for fix for https://github.com/Unvanquished/Unvanquished/issues/2320

### CODE REVIEW

**Comment by illwieckz** [comment]
Needed by https://github.com/Unvanquished/Unvanquished/pull/2323

**Comment by DolceTriade** [comment]
lgtm

**Comment by sweet235** [comment]
That does not seem to fix https://github.com/Unvanquished/Unvanquished/issues/2320

**Comment by sweet235** [comment]
It might work, i didnt merge another correspondig PR.

**Comment by illwieckz** [comment]
Yeah, you likely have a repository mismatch, I confirm it works.

Before:

[spectator scoreboard](https://dl.illwieckz.net/b/unvanquished/bugs/spectator-scoreboard/unvanquished_2022-12-03_081736_000.jpg)

After:

[spectator scoreboard](https://dl.illwieckz.net/b/unvanquished/bugs/spectator-scoreboard/unvanquished_2022-12-03_082445_000.jpg)

**Pull request merged**
