### PR TITLE
ui/scoreboard: display who is the winner, fix Unvanquished/Unvanquished#434

### PR DESCRIPTION
**Pull request by illwieckz**
Display who is the winner, to fix Unvanquished/Unvanquished#434

### CODE REVIEW

**Comment by slipher** [comment]
This can be done without adding a new element type.

- Change the line `<winner/>` to `<inlinecvar cvar="ui_winner" class="winner" />`
- Change the line `winner` to `.winner`

**Comment by illwieckz** [comment]
It works but it looks bad:

[winner in scoreboard](https://dl.illwieckz.net/b/unvanquished/bugs/winner-in-scoreboard/unvanquished_2020-09-27_211321_000.jpg)

**Comment by illwieckz** [comment]
OK, with some CSS tweaks it works correctly:

[winner in scoreboard](https://dl.illwieckz.net/b/unvanquished/bugs/winner-in-scoreboard/unvanquished_2020-09-28_005341_000.jpg)

[winner in scoreboard](https://dl.illwieckz.net/b/unvanquished/bugs/winner-in-scoreboard/unvanquished_2020-09-28_005833_000.jpg)

**Comment by illwieckz** [comment]
PR is ready.

**Comment by slipher** [comment]
Good to go

**Pull request merged**
