### PR TITLE
buildings: new icons

### PR DESCRIPTION
**Pull request by Gireen**
pngs exported from inkscape with
`for f in *.svg; do inkscape $f -e "${f%.*}.png"; done
`

### CODE REVIEW

**Comment by DolceTriade** [comment]
No hive icon?

**Comment by DolceTriade** [comment]
Screenshots:

**Comment by Gireen** [comment]
yes are no hive and spiker icon. the buildings look with booster so similar that they maybe require a more symbolic icon that the building shape.

**Comment by DolceTriade** [comment]
Spiker icon is fine tbh. It' not super detailed. The Hive...idk. Anyways lgtm

**Review by DolceTriade — APPROVED** [review]

**Comment by illwieckz** [comment]
The leech is small compared to others.
The egg may be smaller (more perceived margin)

**Comment by illwieckz** [comment]
@Gireen I just invited you to the organization so you can push into branches we can modify before merging.

**Comment by illwieckz** [comment]
Merged. I also resized a bit leech and egg to get their size more consistent with others:

unvanquished_2023-01-16_141322_000

I then merged the branch.

**Pull request closed without merging**
