### PR TITLE
prefer pulse to luci to defend base

### PR DESCRIPTION
**Pull request by bmorel**
buy equipment before going to repair, to have armors in case of attack

### CODE REVIEW

**Comment by slipher** [comment]
I wonder if pulse rifle could be problematic with teamkilling the base too... Well, it's probably an improvement on the status quo, LGTM

**Comment by bmorel** [comment]
> Well, it's probably an improvement on the status quo, LGTM

From my testing, it's globally better, but to be honest, it's far from perfect: distance might require tweaking, and distance of the target compared to any friendly building should also be taken into consideration. Sadly, those changes are a less trivial, and if using any building in current state of things, the code would be become less maitainable (and BTs are already not the friendliest piece of code)

**Comment by bmorel** [comment]
Regarding pulse for friendly fire, it is true that sometimes they miss target, but pulse is a lot less dangerous than luci, which they *always* charge to 50% and which have a rather wide explosion radius

**Comment by bmorel** [comment]
Nobody seems against.

**Pull request merged**
