### PR TITLE
implement ghost-yellow shader

### PR DESCRIPTION
**Pull request by bmorel**
Those files were previously in res-buildables_src repo, but I think this
does not really makes sense.

### CODE REVIEW

**Comment by illwieckz** [comment]
Just replace `yellowbuild.png` with optimized https://dl.illwieckz.net/j/yellowbuild.png and everything would be fine for me.

**Comment by bmorel** [comment]
@illwieckz : done.

**Review by necessarily-equal — APPROVED** [review]
LGTM

**Comment by slipher** [comment]
Links! https://github.com/Unvanquished/Unvanquished/pull/1617 https://github.com/UnvanquishedAssets/res-buildables_src.dpkdir/pull/7

I suppose it's smart to move it here, so that we can use the new feature without having to load more unreleased paks besides `unvanquished_src`. :+1:

**Pull request merged**
