### PR TITLE
Grenade use

### PR DESCRIPTION
**Pull request by bmorel**
Teach bots how to use grenades

### CODE REVIEW

**Comment by slipher** [comment]
Can you make it distance to *any* human buildable, not just reactor? It's very frustrating when bots on my team destroy our own base (as they do with luci).

**Comment by illwieckz** [comment]
Example of bot nading an outpost (video from September, on bot server):

[bot outpost grenade](https://dl.illwieckz.net/b/unvanquished/bugs/bot-grenade-outpost/20210912-032602-000.unvanquished-bot-grenade-outpost.webm)

In fact every wave of bots returning to armoury (bought and) dropped between 1 to 3 grenades in the base.

**Comment by bmorel** [comment]
> Can you make it distance to any human buildable, not just reactor? It's very frustrating when bots on my team destroy our own base (as they do with luci).

Sadly, unvanquished lacks such feature, currently it would require listing *all* the buildings one by one. That feature would also be useful for aliens to defend properly when close enough to *any* alien building, and would ofc also be useful for lucifer.
Keep in mind that, currently, grenade buying is disabled by default, though, and that adding that "friendly" or "enemy" keywords in BT would require 2 PRs to be synced.

**Comment by bmorel** [comment]
> In fact every wave of bots returning to armoury (bought and) dropped between 1 to 3 grenades in the base.

Interesting. Were they alerted to some alien presence?

**Comment by slipher** [comment]
You could add a pseudo-entity for closest building of a team. Similar to how there is `E_ENEMY` for some enemy.

**Comment by bmorel** [comment]
Yet, that'd be the solution, and it would be useful for much more AI stuff. Now, that E_ENEMY thingy is, AFAIK, not tested on the field, and adding E_ALLY (and E_NEUTRAL in the process, maybe? Which would exclude spectators, ofc) might be more work than expected.
Not really in the scope of this fairly simple PR.

**Comment by slipher** [comment]
How about something like this https://github.com/Unvanquished/Unvanquished/pull/1666

**Comment by slipher** [comment]
> How about something like this Unvanquished/Unvanquished#1666
merged

**Comment by bmorel** [comment]
Nice, this will trigger few tweaks in the BTs, but let's start with this obvious one!

**Comment by bmorel** [comment]
@slipher @illwieckz is that ok now? (considering the fact bots still can't buy grenades by default, which would require a PR to unvanquished itself to change)

**Comment by slipher** [comment]
LGTM

**Pull request merged**
