### PR TITLE
Add UI for more bot CVar equipment/classes

### PR DESCRIPTION
**Pull request by bmorel**
* light armor
* medium armor
* battlesuit
* firebomb
* grenade
* radar
* granger
* adv granger
* dretch

Note that bots will still spawn as dretch or naked+SMG, but will switch to lesser choices when they can if SMG(not dretch because aliens bots can't devolve) are forbidden by those CVars.

### CODE REVIEW

**Comment by slipher** [comment]
The commit adds options only for Dretch, Granger, and Advanced Granger. But grangers are forbidden and dretch is mandatory, so none of the options is useful.

**Comment by bmorel** [comment]
Ah, something went wrong in the process then. I'll fix that "soon"

**Comment by bmorel** [comment]
@slipher: Dretch, granger and adv grangers have been removed.

**Comment by slipher** [comment]
You already added options for these below the weapon ones.

**Comment by bmorel** [comment]
Ohh... right, I guess it was some weird stuff from my side. Mea culpa!

**Pull request closed without merging**
