### PR TITLE
Migrate from libRocket to RmlUi

### PR DESCRIPTION
**Pull request by slipher**
Companion https://github.com/Unvanquished/Unvanquished/pull/1715

### CODE REVIEW

**Comment by slipher** [comment]
Event names MUST be lowercase in RmlUi.

Size tweaks were needed because the CSS engine changed or something, so that some elements ended up with different sizes with RmlUi vs. with libRocket.

**Comment by illwieckz** [comment]
The RML part looks good to me (as soon as it produces the expected result).

**Comment by bmorel** [comment]
> Event names MUST be lowercase in RmlUi.

Ah, sad.
But looking at libRocket's examples, it is likely that this could work with libRocket too, so it would be possible to get that part in a different PR for immediate merge, which is easier to try, especially now that there is a nightly build server. It would also make the review significantly easier (even if I already looked at the code and seen no problem).

**Comment by illwieckz** [comment]
I added a commit to fix the server browser tabs to be displayed on the left. This is the only visual discrepancy I have seen so far.

**Comment by illwieckz** [comment]
Oh no, this one was merged to `master`.

**Comment by illwieckz** [comment]
I merged the branch to `0.53.0/sync` instead and returned `master` to initial state.

**Comment by illwieckz** [comment]
if you have pulled unvanquished_src.dpkdir master before, you have to reset to 2b70d5cb3819559faa73d228c12fe1fd54b9de9f

**Pull request merged**
